# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'APP.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import cv2
cam = cv2.VideoCapture(0)

class camera:
    def __readcamera():
        ret, frame = cam.read()
        cv2.resize(frame, (640, 480))
        return frame

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Camera = QtWidgets.QLabel(self.centralwidget)
        self.Camera.setGeometry(QtCore.QRect(10, 100, 640, 480))
        self.Camera.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Camera.setFont(font)
        self.Camera.setObjectName("Camera")
        self.Capture = QtWidgets.QPushButton(self.centralwidget)
        self.Capture.setGeometry(QtCore.QRect(700, 310, 299, 61))
        self.Capture.setObjectName("Capture")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(700, 370, 299, 31))
        self.label_3.setObjectName("label_3")
        self.input_buah_jatuh = QtWidgets.QSpinBox(self.centralwidget)
        self.input_buah_jatuh.setGeometry(QtCore.QRect(700, 410, 299, 26))
        self.input_buah_jatuh.setObjectName("input_buah_jatuh")
        self.btn_Input_buah_jatuh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Input_buah_jatuh.setGeometry(QtCore.QRect(700, 450, 299, 61))
        self.btn_Input_buah_jatuh.setObjectName("btn_Input_buah_jatuh")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(700, 520, 297, 41))
        self.label_2.setObjectName("label_2")
        self.Camera_2 = QtWidgets.QLabel(self.centralwidget)
        self.Camera_2.setGeometry(QtCore.QRect(720, 100, 256, 192))
        self.Camera_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Camera_2.setFont(font)
        self.Camera_2.setObjectName("Camera_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Harvesting Sickle"))
        self.label.setText(_translate("MainWindow", "Harvesting Sickle"))
        self.Camera.setText(_translate("MainWindow", "Camera"))
        self.Capture.setText(_translate("MainWindow", "Capture"))
        self.label_3.setText(_translate("MainWindow", "Input Buah Jatuh"))
        self.btn_Input_buah_jatuh.setText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Result"))
        self.Camera_2.setText(_translate("MainWindow", "Camera"))
        
        
def main() -> None:
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
            
if __name__ == "__main__":
    main()
